<?php
$systemLog = 'apps loader';
require '../classes/language.php';
require '../../lib_mobphp/chtml.php';
require '../../lib_mobphp/dbio.php';

//////////////////////////////////////////////////////////////////////////////// 
//
//  IMPORTS APPOINTMENTS FROM MEDOFFICE EXPORTS - link patients through their dossier number
//
//  pre-requisite: exported patients from i-agenda are loaded into the mobminder with dossier number as reference field. 
//  now that patients are imported in mobminder, you can use this utility to import the agenda file provided by medi-soft
//
//	following columns are expected:
//
//  appdate	appfrom	appto reference	note performance
//
//
//  Usage: http://127.0.0.1/utilities/medoffice.php?id=3277&rsc=8905   <= test mode
//  Usage: http://127.0.0.1/utilities/medoffice.php?id=3277&rsc=8905&cleanup=1&do=1   <= clean up and action mode
// 
//  http://be.mobminder.com/utilities/mobikap.php?id=3277&rsc=8905&do=1
//
//  !! The filename has a rigid format, like 2891_7160_apps.csv';
//
//  !! IMPORT VISITORS FIRST !!

//////////////////////////////////////////////////////
//
//  catch this script name 
//
$pathfile = $_SERVER["SCRIPT_NAME"];
$break = Explode('/', $pathfile);
$thisScript = $break[count($break) - 1]; 


//////////////////////////////////////////////////////
//
//  HTML Headers 
//
$html = new C_html();
$html->pushMeta('Content-Type'			, 'text/html; charset=UTF-8');
$html->pushMeta('Content-Style-Type'	, 'text/css');
$html->pushMeta('Content-Script-Type'	, 'text/javascript');
$html->pushMeta('pragma'				, 'no-cache');
$html->pushLink('visiload.css'			, 'stylesheet'	, 'text/css');
$html->pageTitle('mobminder appointments csv loader');
$html->pushHTML('<h1>mobminder appointments generator</h1>');



//////////////////////////////////////////////////////
//
//  Echo functions
//
function error($msg, $handle = false) { global $html; if($handle) fclose($handle); $html->pushHTML('<h3>'.$msg.'</h3>'); $html->dropPage(); die(); }
function notice($msg) { global $html; $html->pushHTML('<p>'.$msg.'</p>'); }

function remove_utf8_bom($text) {
	$bom = pack('H*','EFBBBF');
	$text = preg_replace("/^$bom/", '', $text);
	return $text;
}
	
function tolines($handle, $ext, $encoding = false) {
	
	$lines = Array();
		
			if(!$handle) return $lines;
			
			$c = 0; $bunch = '';
		
		if(!$encoding) {
			while(!feof($handle) && $c++<200)	$bunch .= trim(fgets($handle)); rewind($handle);
			$encoding = mb_detect_encoding($bunch, mb_list_encodings(), true);
			notice('Detected file encoding is:'.$encoding);
			// Note about encoding:
			//   Windows .xls and .xlsx files are ISO-8859-1
			//   Flat files generated by Octopus are ASCII
			//   Backups generated by Mobminder are UTF-8
		} else {
			notice('You have specified file encoding:'.$encoding);
			if($encoding!='UTF-8' && $encoding!='ISO-8859-1' && $encoding!='ASCII') {
				$encoding ='UTF-8';
				notice('Your file encoding specification is not supported, default:'.$encoding.' (it should be one of UTF-8, ISO-8859-1, ASCII)');
			}
		}
		
			// multi lines fields (mlf) are changing the pattern of having one record by line in the csv (*csv*)
			//
			// - Velden met embedded separator moeten quoted zijn. Bv: “tekst met een ; erin”
			// - Velden met embedded double quotes moeten quoted zijn. Bv: ”tekst met ””double”” quotes”. Let op : de embedded quotes moeten verdubbeld worden.
			// - Velden met embedded line breaks moeten quoted zijn. Let op: line break = chr(10), niet backslash n.
			//
			// example:
			// 		id	;resources	;cueIn				;cueOut				;note
			// 		3	;EL			;2015-01-06 10:00	;2015-01-06 11:00	;MME POMEROLE NOTIFIEE
			// 		4	;EL			;2015-01-06 15:00	;2015-01-06 16:00	;M.CONDé
			// 		5	;PE			;2015-11-26 00:00	;2015-11-27 00:00	;"IRTS college coopératif
			// 		JE SUIS EN EXTERIEUR TTE LA JOURNEE
			// 		sur le thème de ""les nouvelles figures de l'intervention sociale""
			// 		organisé par le collège coopératif sur le site de IRTS Salliens."
			// 		6	;EL			;2015-01-07 08:30	;2015-01-07 12:30	;REUNION USAGERS
			// 		7	;EL			;2015-01-13 00:00	;2015-01-14 00:00	;BAYONA Abs
			//
			// item 5 is not following the regular pattern (one line per record)
			// mlf opens when an odd number of '"' is present and they close by the same rule. 
			// Inside an mlf double quotes are simply doubled : '""'
			//
			// see also (*as*) as how escapable characters are handled through DB and client js interface
			//
			$mlf_ongoing = false; $mlf_off = false; $mlf_start = false; $buffer = ''; $c = 0;
			
			$filter_line = utf8_encode('/[^#_ÀàâãçËÈÉéèëêôöîïñûüùÿ@ A-Za-z0-9+€&:;,!=\*\?\/\'\"\.\(\)\[\]\-]/');
			$filter_substitute = utf8_encode('_');
				
		while(!feof($handle)) {
			
			$line = trim(fgets($handle)); if($line=='') continue; // $lines will contains ONLY non blank lines
			if($c==0) if($encoding=='UTF-8') $line = remove_utf8_bom($line);
			$mlf_start = false; $mlf_off = false; 
			
			$slimit = false; // mlf do not apply to any file format but .csv
			if($ext == 'csv') { $dquotes = substr_count($line, '"'); $slimit = $dquotes%2; } // that is 0 if 0, 2, 4 and 1 if 1, 3, 5 occurences.
			if($slimit) {
				if($mlf_ongoing) $mlf_off = true; // this line finishes an excel string (multiple lines)
				else $mlf_start = true;  // this line opens an excel string (multiple lines)
				$mlf_ongoing = !$mlf_ongoing;
			} 
			$mlf = $mlf_ongoing||$mlf_off;
			
			// ISO treatment
			$utf8 = $line; // default is UTF-8 assumed
			if($ext == 'csv') { // see if we need to convert to UTF-8
				$line = preg_replace('/[\x00-\x1F\x7F]/','',$line); // removes special chars (passed by Octopus)
				if($encoding!='UTF-8') $utf8 = iconv('ISO-8859-1', 'UTF-8', $line);
			} 
			$utf8 = preg_replace($filter_line,$filter_substitute,$utf8); // removes other not alphanum chars
			
			// utf8 treatment
			$utf8 = preg_replace("/\\s\\s+/",' ',$utf8); // reduces multiple spaces into single spaces
			
			if($mlf) {
				if($mlf_off) $utf8 = rtrim($utf8, '\"'); // removes the trailing double quote (or [double quote + ;] if a field follows)
				if($mlf_start) $buffer = $utf8; else $buffer .= '\n'.$utf8; // "\n" replaces the chr(10) in the stream
				if(!$mlf_off) continue; // continues filling buffer up to the exepcted mlf_off line
			} 
			else $buffer = $utf8; // non mlf case
			
			if($c++<20) notice('line '.$c.' >'.$buffer);
			$lines[] = $buffer; unset($buffer); $buffer = '';
		}
		fclose($handle);
		return $lines;
	}


//////////////////////////////////////////////////////////////////////////////// 
//
//  CHECKING INPUTS AND FILE
//
if(isset($_GET['id'])) $groupId = $_GET['id']; else $groupId = false;
if(isset($_GET['rsc'])) $rescId = $_GET['rsc']; else $rescId = false;
if(isset($_GET['cleanup'])) $cleanup = true; else $cleanup = false;
if(isset($_GET['do'])) $do = true; else $do = false;


if(!$groupId) error('You need to give an account id');

$o_dS_group = new C_dS_group($groupId);
if($o_dS_group->name == '') error('The account does not exists');
$html->pushHTML('<h2>Account identified: '.$o_dS_group->name.'</h2>');

//

if(!$rescId) error('You need to give a resource id');

$o_dbAccess_resources = new C_dbAccess_resources($groupId); 
$rcount = $o_dbAccess_resources->count();
if (!$rcount) error('No resource found!');
	else 
		$html->pushHTML('<h2>Resources identified: '.$rcount.' resources</h2>');

$o_dS_resource = $o_dbAccess_resources->keyed[$rescId];
if (!$o_dS_resource) error('No resource found with rescId: bCal!'.$rescId);
	else 
		$html->pushHTML('<h2>Appointments are going to be created for: '.$o_dS_resource->name.'</h2>');
	
$filename = $groupId.'_'.$rescId.'_apps.csv';
if (!file_exists($filename)) error('No corresponding csv file: '.$filename);

$handle = fopen($filename,'r');
if(!$handle) error('The file exists but could not be opened: '.$filename);

$line1 = fgets($handle);
if($line1=='') error('The file is empty: '.$filename, $handle);

$html->pushHTML('<h2>File opened: '.$filename.'</h2>');

$html->pushHTML('<p><b>First line: </b>'.$line1.'</p>');

$crlf = 0;
if(substr($line1,-2)==chr(13).chr(10)) { $crlf = 2; $html->pushHTML('<p>Lines are feeded with <b>CRLF</b></p>'); }
	else if(substr($line1,-1)==chr(10)) { $crlf = 1; $html->pushHTML('<p>Lines are feeded with <b>LF</b></p>'); };

$headers = explode(';',substr($line1,0,-$crlf)); // strips CRLF

if(!in_array('appdate',$headers)) error('Missing mandatory header: appdate', $handle);
if(!in_array('appfrom',$headers)) error('Missing mandatory header: appfrom', $handle);
if(!in_array('appto',$headers)) error('Missing mandatory header: appto', $handle);
if(!in_array('patientid',$headers)) error('Missing mandatory header: patientid', $handle);
if(!in_array('note',$headers)) error('Missing mandatory header: note', $handle);


// mandatory fields
$ad_position = array_keys($headers, 'appdate'); 	$ad_position = $ad_position[0]; 
$af_position = array_keys($headers, 'appfrom'); 	$af_position = $af_position[0]; 
$at_position = array_keys($headers, 'appto'); 		$at_position = $at_position[0]; 
$rf_position = array_keys($headers, 'reference'); 	$rf_position = $rf_position[0]; 
$nt_position = array_keys($headers, 'note'); 		$nt_position = $nt_position[0]; 
$pf_position = array_keys($headers, 'performance'); $pf_position = $pf_position[0]; 

$hcount = count($headers);


//////////////////////////////////////////////////////////////////////////////// 
//
//  READING THE FILE
//

$lines = tolines($handle, 'csv');

$cuein = microtime(true);
$lcount = 0; $skipcount = 0; $ccount = $hcount-1; $table = array();
function normal(&$item, $key) { if(isset($item)) $item = trim($item); else $item=''; };
foreach($lines as $line) {
	$lcount++; $comascount = substr_count($line, ';');
	if($comascount != $ccount) { // may be an empty line, anyway it doesnt count the right number of cells!
		$skipcount++; notice('<b>Skipping line: </b>'.$lcount.' (columns count does not match:'.$ccount.' expected, '.$comascount.' found)'); continue; }; 
	
	$split = explode(';',$line);
	array_walk($split,'normal');
	$table[] = $split;
}
$cueout = microtime(true);
$cuedelta = (($cueout-$cuein)*1000)|0;
$lcount -= $skipcount;
$html->pushHTML('<h2>The file has been read in: '.$cuedelta.' mseconds, it counts '.$lcount.' valid lines</h2>');
if(!$lcount) error('No valid lines can be inserted in the DB');



//////////////////////////////////////////////////////////////////////////////// 
//
//  LOADING VISITORS
//
$cuein = microtime(true); $visiTotal = 0;

$byRegist = Array(); // an array that references the visitors using their original id from (id in the migrated DB)
$byName = Array(); // an array that references the visitors using their original id from (id in the migrated DB)
$byNameBd = Array(); // an array that references the visitors using their original id from (id in the migrated DB)

	$SQL = 'SELECT id, reference, lastname, firstname, birthday FROM visitors WHERE groupId = '.$groupId.';';

	$result = C_dbIO::q($SQL);
	while ($row = $result->fetch_array()) {
			$r = $row['reference'];
		if($r) $byRegist[$r] = $row['id'];
			$l = $row['lastname'];
			$f = $row['firstname'];
			$b = $row['birthday'];
				$by = substr($b,0,4);
				$bm = substr($b,4,2);
				$bd = substr($b,6,2);
			$reference = strtolower($l.' '.$f);
		$byName[$reference] = $row['id'];
			$reference = strtolower($reference.' '.$bd.'/'.$bm.'/'.$by);
		$byNameBd[$reference] = $row['id'];
		$visiTotal++;
	}
	$result->close();
		
$cueout = microtime(true);
$cuedelta = (($cueout-$cuein)*1000)|0;
$html->pushHTML('<h2>'.$visiTotal.' visitors have been loaded in: '.$cuedelta.' mseconds</h2>');


if($do)
	$html->pushHTML('<h2>DO MODE IS ACTIVE !</h2>');


//////////////////////////////////////////////////////////////////////////////// 
//
//  ANNOUNCE JOB START TEST COMPLETION
//
$total = $lcount;
$from = @$_GET['f']; 	// generated by this parser when it calls itself
$limit = 2000;
if(!isset($from)) { // then this page is called for the first time, echo request for sending
	
		if($cleanup) {

		$q = new Q('select id from reservations where groupId  = '.$groupId.';');
			$resaIds = $q->ids();
			
			if($resaIds != '') {
				new Q('DELETE FROM attendees WHERE groupId IN ('.$resaIds.');');
				new Q('DELETE FROM att_visitors WHERE groupId IN ('.$resaIds.');');
				new Q('DELETE FROM reservations WHERE id IN ('.$resaIds.');');
			}
			
			// archive table
			$q = new Q('select id from archive_reservations where groupId  = '.$groupId.';');
			$resaIds = $q->ids();
			
			if($resaIds != '') {
				new Q('DELETE FROM archive_attendees WHERE groupId IN ('.$resaIds.');');
				new Q('DELETE FROM archive_att_visitors WHERE groupId IN ('.$resaIds.');');
				new Q('DELETE FROM archive_reservations WHERE id IN ('.$resaIds.');');
			}
			
			$html->pushHTML('<h2>CLEAN UP COMPLETE !</h2>');
		}	
	
		$d = ''; if($do) $d = '&do=1';
		$a = $thisScript.'?id='.$groupId.'&rsc='.$rescId.'&f=1'.$d;
		
	$html->pushHTML('<h1>Ready to start the job, by bunches of '.$limit.' items</h1>');
	$html->pushHTML('<a href="'.$a.'">Click to Start creating the appointments</a>');
	$html->dropPage(); 
	die();
}

//////////////////////////////////////////////////////////////////////////////// 
//
//  LOADING VISITORS
//


//////////////////////////////////////////////////////////////////////////////// 
//
//  BUILDING UP DATA SETS
//

$cuein = microtime(true);
$SQL = array();
$icount = 0; $iscan = 0; $to = ($from+$limit-1); $nomatch = 0; $newVisiCount = 0;
for($x = $from-1; $x<$to; $x++,$from++) { 
		
		if($from>=$lcount) break;
		$iscan++;
		$split = $table[$x];
		$date = $split[$ad_position]; 
		$timein = $split[$af_position]; 
		$timeout = $split[$at_position]; 
		$patientid = strtolower($split[$rf_position]); 
		$appNote = $split[$nt_position]; 
			
		$visiId = false; $match = '';
		if($patientid) {
			if(isset($byRegist[$patientid])) {
				$visiId = $byRegist[$patientid];
				$match = 'match on patient id';
			}
		} 
		
				// $dd = substr($date,0,2); // date is originally in mobikap like 26-08-16
				// $mm = substr($date,3,2);
				// $yyyy = '20'.substr($date,-2);
				// $daty = $yyyy.'-'.$mm.'-'.$dd; // like 2016-08-26
				$daty = str_replace('/', '-', $date);
				$timein = str_replace('h', ':', $timein);
				$timeout = str_replace('h', ':', $timeout);
			$datyIn = $daty.' '.$timein;
			$datyOut = $daty.' '.$timeout;
			$cueIn = new C_date($datyIn);
			$cueOut = new C_date($datyOut);
			
		$o_dS_reservation = new C_dS_reservation(false, $groupId);
		$o_dS_reservation->cueIn = $cueIn->getTstmp();
		$o_dS_reservation->cueOut = $cueOut->getTstmp();
		$o_dS_reservation->note = $appNote;
			notice('<b>Appointment: </b>'.$match.' => '.$cueIn->getDateTimeString().' to '.$cueOut->getDateTimeString().' with '.$name); // debug
		if($do) $o_dS_reservation->dSsave();
		$resaId = $o_dS_reservation->id;
		
		$o_dS_attendee = new C_dS_attendee(false, $resaId);
		$o_dS_attendee->resourceId = $o_dS_resource->id;
		$o_dS_attendee->resourceType = $o_dS_resource->resourceType;
		
		if($visiId) {
			$o_dS_att_visitor = new C_dS_att_visitor(false, $resaId);
			$o_dS_att_visitor->resourceId = $visiId;
			$o_dS_att_visitor->resourceType = class_visitor;
			if($do) $o_dS_att_visitor->dSsave();
		}
		
		if($do) $o_dS_attendee->dSsave();
		$icount++;
}
$cueout = microtime(true);
$cuedelta = (($cueout-$cuein)*1000)|0;
	notice('<b>New visitors must be created: </b>'.$newVisiCount.' in total.');

if($do) 
	$html->pushHTML('<h2>'.$icount.' items have been inserted (do not re-execute! or clean-up first), '.$iscan.' were scanned. Scanned in: '.$cuedelta.' mseconds</h2>');
else
	$html->pushHTML('<h2>'.$icount.' items have been prepared (not in do mode), '.$iscan.' were scanned. Scanned in: '.$cuedelta.' mseconds</h2>');



//////////////////////////////////////////////////////////////////////////////// 
//
//  L O O P I N G
//
if($from < $total) {
	$html->pushHTML('<h1>Job not complete, ready to send the next bunch, from '.$from.', '.$limit.' more items</h1>');
		$d = ''; if($do) $d = '&do=1';
		$a = $thisScript.'?id='.$groupId.'&rsc='.$rescId.'&f='.$from.$d;
	$html->pushHTML('<a href="'.$a.'">Click to Start sending next bunch</a>');
	$html->dropPage(); 
	die();
}

//////////////////////////////////////////////////////////////////////////////// 
//
//  END OF JOB
//

$html->pushHTML('<h2>Operation SUCCESSFULL: do NOT re-execute this page.</h2>');
$html->dropPage();


?>