<?php


require '../../classes/language.php';
require '../../../lib_mobphp/chtml.php';
require '../../../lib_mobphp/dbio.php';

ini_set('memory_limit', '1024M');
 
//////////////////////////////////////////////////////////////////////////////// 
//
//  Utililib is a library that helps LOADING csv files 
//
//  FROM .CSV FILES to a MOBMINDER ACCOUNT
//


//////////////////////////////////////////////////////
//
//  Echo functions
//
$out = '';
function error($msg, $handle = false) { 
	global $out;
	if($handle) { fclose($handle); }
	$out.='<h3>'.$msg.'</h3>'; 
	echo html($out); 
	die('<br/>Ending execution'); 
}

function deltasec($i,$o) { $seconds = (((($o-$i)*1000)|0)/1000); return $seconds.'sec'; } // $i and $o are microseconds, output is seconds coma milliseconds
function h1($t) { return '<h1 style="white-space:nowrap; color:#7595AF; font-size:1.4em; padding-top:2em;">'.$t.'</h1>'; }
function h2($t) { return '<h2 style="white-space:nowrap; color:	#a4b357; font-size:1.1em; font-weight:bold; padding-top:1.6em;">'.$t.'</h2>'; }
function h3($t) { return '<h3 style="white-space:nowrap; color:	silver; font-size:1.1em; font-weight:normal; margin-left:3em; margin-bottom:2em; padding-top:.6em;">'.$t.'</h3>'; }
function notice($msg, $indent=2) { return '<p style="padding-left:'.$indent.'em;">'.$msg.'</p>'; }
function warning($msg, $indent=0) { return '<p style="color:orange; padding-left:'.$indent.'em;">'.$msg.'</p>'; }
function red($msg, $indent=0) { return '<p style="color:red; padding-left:'.$indent.'em;">'.$msg.'</p>'; }
function blue($msg, $indent=0) { return '<p style="color:blue; padding-left:'.$indent.'em;">'.$msg.'</p>'; }
function micro($msg, $indent=3) { return '<p style="color:blue; padding-left:'.$indent.'em; font-size:80%; line-height:70%;">'.$msg.'</p>'; }
function microtab($msg, $indent=6) { return '<p style="color:red; padding-left:'.$indent.'em; font-size:75%; line-height:70%;">'.$msg.'</p>'; }
function hrefbutton($caption, $href) { return '<div class="button"><a href="'.$href.'">'.$caption.'</a></div>'; }
function html($content) {
		$pathfile = $_SERVER["SCRIPT_NAME"];
		$break = Explode('/', $pathfile);
		$thisScript = $break[count($break) - 1]; 

		$o = '<!DOCTYPE HTML>';
		$o .= '<html>';
			$o .= '<head>';
			$o .= '<title>'.$thisScript.'</title>';
			$o .= '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">';
			$o .= '<link href="../utilities.css" rel="stylesheet" type="text/css">';
			$o .= '<head>';
		$o .= '<body>'.$content.'</body></html>';
		return $o;
}


//////////////////////////////////////////////////////////////////////////////// 
//
//  READING THE FILE ( considers multi-line fields as per csv standard )
//

function normal(&$item, $key) { // this function is applied to each and single field (*#*)
	if(isset($item)) $item = trim($item); else $item=''; 
};

function remove_utf8_bom($text) {
	$bom = pack('H*','EFBBBF');
	$text = preg_replace("/^$bom/", '', $text);
	return $text;
}

	define('detect_encoding', false);
function tolines($handle, $encoding = detect_encoding, $tolower = true) { // the default file encoding by MS Excel when saving in csv format
	global $out;
	$lines = Array(); // returns a 2 dimensional array of file [lines][header]
	
		$c = 0; $bunch = '';
		$filter_line 		= utf8_encode('/[^#_¿‡‚„ÁÀ»…ÈËÎÍÙˆÓÔÒ˚¸˘ˇ@ A-Za-z0-9+Ä&:;,!=\*\?\/\'\"\.\(\)\[\]\-]/');
		$filter_substitute 	= utf8_encode('_');
	
	if(!$encoding) { // can be 'ISO-8859-1','UTF-8' sse php doc
		while(!feof($handle) && $c++<200) $bunch .= trim(fgets($handle)); rewind($handle); $line1 = fgets($handle);
		$encoding = mb_detect_encoding($bunch, mb_list_encodings(), true);
		$out.= notice('Detected file encoding is:'.$encoding);
		// Note about encoding:
		//   Windows .xls and .xlsx files are ISO-8859-1
		//   Flat files generated by Octopus are ASCII
		//   Backups generated by Mobminder are UTF-8
	} else {
		$out.= notice('You have specified file encoding:'.$encoding);
		if($encoding!='UTF-8' && $encoding!='ISO-8859-1' && $encoding!='ASCII') {
			$encoding ='UTF-8';
			error('Your file encoding specification is not supported, default:'.$encoding.' (it should be one of UTF-8, ISO-8859-1, ASCII)');
		}
	}
	
		// multi lines fields (mlf) are changing the pattern of having one record by line in the csv (*csv*)
		//
		// - Velden met embedded separator moeten quoted zijn. Bv: ìtekst met een ; erinî
		// - Velden met embedded double quotes moeten quoted zijn. Bv: îtekst met îîdoubleîî quotesî. Let op : de embedded quotes moeten verdubbeld worden.
		// - Velden met embedded line breaks moeten quoted zijn. Let op: line break = chr(10), niet backslash n.
		//
		// example:
		// 		id	;resources	;cueIn				;cueOut				;note
		// 		3	;EL			;2015-01-06 10:00	;2015-01-06 11:00	;MME POMEROLE NOTIFIEE
		// 		4	;EL			;2015-01-06 15:00	;2015-01-06 16:00	;M.CONDÈ
		// 		5	;PE			;2015-11-26 00:00	;2015-11-27 00:00	;"IRTS college coopÈratif
		// 		JE SUIS EN EXTERIEUR TTE LA JOURNEE
		// 		sur le thËme de ""les nouvelles figures de l'intervention sociale""
		// 		organisÈ par le collËge coopÈratif sur le site de IRTS Salliens."
		// 		6	;EL			;2015-01-07 08:30	;2015-01-07 12:30	;REUNION USAGERS
		// 		7	;EL			;2015-01-13 00:00	;2015-01-14 00:00	;BAYONA Abs
		//
		// item 5 is not following the regular pattern (one line per record)
		// mlf opens when an odd number of '"' is present and they close by the same rule. 
		// Inside an mlf double quotes are simply doubled : '""'
		//
		// see also (*as*) as how escapable characters are handled through DB and client js interface
		//
		$mlf_ongoing = false; $mlf_off = false; $mlf_start = false; $buffer = ''; $c = 0;
	while(!feof($handle)) {
		
		$line = trim(fgets($handle)); if($line=='') continue; // $lines will contains ONLY non blank lines
		if($c==0) if($encoding=='UTF-8') $line = remove_utf8_bom($line);
		$mlf_start = false; $mlf_off = false; 
		
		$dquotes = substr_count($line, '"'); $slimit = $dquotes%2; // that is 0 if 0, 2, 4 and 1 if 1, 3, 5 occurences.
		if($slimit) {
			if($mlf_ongoing) $mlf_off = true; // this line finishes an excel string (multiple lines)
			else $mlf_start = true;  // this line opens an excel string (multiple lines)
			$mlf_ongoing = !$mlf_ongoing;
		} 
		$mlf = $mlf_ongoing||$mlf_off;
		
		// ISO treatment
		$utf8 = $line; // default is UTF-8 assumed
		
		// echo '<p style="color:red; margin:0;">'.$c.']'.$utf8.'<p>';
		if($encoding!='UTF-8') $utf8 = iconv($encoding, 'UTF-8', $line); 

		
		if($c<4) $out.= micro('-- line '.$c.' >'.$utf8);
		
		// $utf8 = preg_replace($filter_line, $filter_substitute, $utf8); // removes other not alphanum chars
		
		
		// utf8 treatment
		$utf8 = preg_replace("/\\s\\s+/",' ',$utf8); // reduces multiple spaces into single spaces
		
		if($mlf) {
			if($mlf_off) $utf8 = rtrim($utf8, '\"'); // removes the trailing double quote (or [double quote + ;] if a field follows) see (*t*)
			if($mlf_start) $buffer = $utf8; else $buffer .= '\n'.$utf8; // "\n" replaces the chr(10) in the stream
			if(!$mlf_off) continue; // continues filling buffer up to the expected mlf_off line
		} 
		else $buffer = $utf8; // non mlf case
		
		if($tolower) $buffer = mb_strtolower($buffer, 'UTF-8');
		
		if($c<4) $out.= notice(chr(9).'line '.$c.' >'.$buffer);
		
		$split = explode(';',$buffer);
		array_walk($split,'normal'); //  (*#*)
		$lines[] = $split; 
		unset($buffer); $buffer = ''; $c++;
	}
	rewind($handle);
	return $lines;
}


?>