nickname=S09
serial_port=/dev/ttyS0
wifi_config_filename=/etc/wpa_supplicant/wpa_supplicant.conf
reporting_number=+32493655599
internet_gateway_ip=192.168.1.1
gateway_server=http://smsgateaway.mobminder.com
lag_default_sec=5
band=DEFAULT
ucs2=true
enable_rpi=true
enable_gprs=false
enable_reporting_sms=true
enable_refreshlag=true
force_signal=false
script_sh_update=./scriptrelease.sh
log_level=log
log_console=true
log_history_day=10
backup_queue_enable=false
queue_read_timeout_sec=60
queue_alive_timeout_sec=5
queue_sendsms_timeout_sec=90
serial_read_timeout_sec=100
gateway_proxy_timeout_sec=5
registration_timeout_counter=10
serial_read_timeout_ms=1000
send_pdu=true
receive_pdu=true

