<?php

$systemLog = 'mobile_fix';
require '../utililib.php';

$allin = microtime(true);
 
//////////////////////////////////////////////////////////////////////////////// 
//
//  Mobiles Load is a script that help LOADING MOBILES lost after a sync with DentAdmin 
//
//  Use a csv file generated by the backup utility from a local backup of the concerned account (i.e. PAROIMPLANT)
//  PVH 2020-12
//	It was re-used after a Medinect maintenance operation on Pole Medical Monique Cornet has deleted 1900 mobiles from visitors files.
//
//   Usage: http://be.mobminder.com/utilities/mobiles_load.php?id=3029
//



//////////////////////////////////////////////////////////////////////////////// 
//
//  CHECKING INPUTS
//
if(isset($_GET['id'])) $accountId = $_GET['id']; else $accountId = false;
if(isset($_GET['do'])) $do = true; else $do = false;


if(!$accountId) error('You need to give an account id');

$o_dS_group = new C_dS_group($accountId);
if($o_dS_group->name == '') error('The account does not exists');

$out .= h2('Account identified: '.$o_dS_group->name);



//////////////////////////////////////////////////////////////////////////////// 
//
//  CHECKING FILE
//
// Identify and open the file
$matches = glob('./'.$accountId.'*.csv');
if(count($matches)>1) error('Multiple files were found have this id in header: '.$accountId.'*.csv, there should be a single file.');
if(count($matches)==0) error('No file was found having this id in header: '.$accountId.'*.csv');
$filename = $matches[0];
if (!file_exists($filename)) error('No corresponding csv file: '.$filename);

$handle = fopen($filename,'r');
if(!$handle) error('The file exists but could not be opened: '.$filename);
$line1 = fgets($handle);
if($line1=='') error('The file is empty: '.$filename, $handle);

$out .= h2('File opened: '.$filename); // from utililib.php
$out .= notice('<b>First line: </b>'.$line1);


$crlf = 0;
if(substr($line1,-2)==chr(13).chr(10)) { $crlf = 2; $out .= notice('Lines are feeded with <b>CRLF</b>'); }
	else if(substr($line1,-1)==chr(10)) { $crlf = 1; $out .= notice('Lines are feeded with <b>LF</b>'); };



//////////////////////////////////////////////////////////////////////////////// 
//
//  CHECKING HEADERS
//

$headers = explode(';',substr($line1,0,-$crlf)); // strips CRLF
if(!in_array('lastname',$headers)) error('Missing mandatory header: lastname', $handle);

C_dS_visitor::$defaults['language'] = language_code_french;
$o_dS_visitor = new C_dS_visitor(); $o_dS_defaults = $o_dS_visitor->getDefaults(); $o_dS_defaults['id'] = 0; $o_dS_defaults['rcolor'] = '';
foreach($headers as $hcount => $header) {
	if(!array_key_exists($header,$o_dS_defaults)) {
			echo('The following header has no correspondance in the target visitor table: '.$header);
			error('The following header has no correspondance in the target visitor table: '.$header, $handle);
		}
}
$out .= h2('Headers are compliant with DB definitions: '.++$hcount.' columns');


//////////////////////////////////////////////////////////////////////////////// 
//
//  READING THE FILE
//


$cuein = microtime(true);
$lcount = 0; $skipcount = 0; $ccount = $hcount-1; 
$lines = tolines($handle); // from utililib.php

$cueout = microtime(true);
$cuedelta = deltasec($cuein,$cueout);
$lcount = count($lines);
$out .= h2('The file has been read in: '.$cuedelta.', it counts '.$lcount.' valid lines');
fclose($handle);
if(!$lcount) error('No valid lines can be inserted in the DB');



	
//////////////////////////////////////////////////////////////////////////////// 
//
//  Existing visitors
//

$mobdb_visitors = new C_dBaccess_visitors(false, $accountId);
$out .= h2('Account visitors loaded: '.$mobdb_visitors->count().' visitors');



//////////////////////////////////////////////////////////////////////////////// 
//
//  POST PROCESSING VISITORS ATTRIBUTES
//

$cuein = microtime(true);
$fnposition = array_keys($headers, 'firstname'); 	$fnposition = $fnposition[0]; 	// position of firstname in the sequence of columns
$lnposition = array_keys($headers, 'lastname'); 	$lnposition = $lnposition[0]; 	// position of firstname in the sequence of columns
$idposition = array_keys($headers, 'id'); 			$idposition = $idposition[0]; 	// position of id in the sequence of columns
$mbposition = array_keys($headers, 'mobile'); 		$mbposition = $mbposition[0]; 	// position of id in the sequence of columns

$out.=notice('idposition:'.$idposition);
$out.=notice('lnposition:'.$lnposition);
$out.=notice('fnposition:'.$fnposition);
$out.=notice('mbposition:'.$mbposition);

$genderColumnIsAbsent = true; if(in_array('gender',$headers)) $genderColumnIsAbsent = false;

	$lcount = 0; 
	$icount = 0;
foreach($lines as $x => $split) {

	$lcount++;
	
	$vid = $split[$idposition];
	$ln = $split[$lnposition];
	$mobile = $split[$mbposition]; $mobile = str_replace('"', '', $mobile);
	
	if(!isset($mobdb_visitors->keyed[$vid])) { $out.= warning('this id is not known from the account visitors ids:'.$vid); continue; }
	
	$dS_visi = $mobdb_visitors->keyed[$vid];
	if($lcount<20) $out .= notice('treating now '.$dS_visi->lastname.' |'.$dS_visi->mobile.'| id:'.$dS_visi->id.' file mobile |'.$mobile.'|');
	if($mobile !== '') 
		if($dS_visi->mobile == '') {
			
			$out .= micro('vId '.$vid.' has no mobile number but one is found in the input file: |'.$mobile.'|, filling in! ('.$ln.')');
			$dS_visi->mobile = $mobile;
			if($do) $dS_visi->dSsave();
			$icount++;
		}
	$mobile = '';
	$vid = '';
}
unset($lines);

$cueout = microtime(true);
$cuedelta = deltasec($cuein,$cueout);




$allout = microtime(true);
$alldelta = deltasec($allin,$allout);
$out .= h2('EXECUTION SUCCESSFULL - Total roundtrip: '.$alldelta.'seconds, '.$icount.' fixed items');

echo html($out); // from utililib.php

?>